services:
  kanboard-db:
    image: mariadb:11
    container_name: kanboard-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - kanboard_internal

  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    restart: unless-stopped
    depends_on:
      - kanboard-db
    environment:
      APPLICATION_URL: ${APPLICATION_URL}
      URL_BASE: ${URL_BASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${KB_PORT:-8021}:80"
    volumes:
      - ./data:/var/www/app/data
      - ./plugins:/var/www/app/plugins
    networks:
      - kanboard_internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.kanboard.rule=PathPrefix(`/kanboard`) || PathPrefix(`/assets`)"
      - "traefik.http.routers.kanboard.entrypoints=web"
      - "traefik.http.routers.kanboard.middlewares=kanboard-strip"
      - "traefik.http.routers.kanboard.priority=100"

      - "traefik.http.middlewares.kanboard-strip.stripPrefix.prefixes=/kanboard"

      - "traefik.http.services.kanboard.loadbalancer.server.port=80"

networks:
  kanboard_internal:
  proxy:
    external: true
