services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - WAIT_FOR_DB=${WAIT_FOR_DB}
    volumes:
      - ./data:/config
    depends_on:
      - bookstack_db
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bookstack.rule=Host(`${BOOKSTACK_DOMAIN}`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.tls.certresolver=letsencrypt"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      - "traefik.http.routers.bookstack-http.rule=Host(`${BOOKSTACK_DOMAIN}`)"
      - "traefik.http.routers.bookstack-http.entrypoints=web"
      - "traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bookstack-http.middlewares=bookstack-https-redirect"

  bookstack_db:
    image: mariadb:11
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge
