services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.traefik.rule=PathPrefix(`/dashboard`) || PathPrefix(`/api`)'
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=admin:${TRAEFIK_AUTH_HASH}'
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
    networks:
      - proxy

networks:
  proxy:
    external: true
