services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    command: start-dev
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}

      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

      - KC_HTTP_RELATIVE_PATH=${KC_HTTP_RELATIVE_PATH}
      - KC_PROXY=${KC_PROXY}
    depends_on:
      - keycloak_db
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.entrypoints=web"

      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  keycloak_db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
