services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      - UPTIME_KUMA_BASE_PATH=/uptime
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:

      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.kuma.rule=PathPrefix(`/uptime`)"
      - "traefik.http.routers.kuma.entrypoints=web"
      - "traefik.http.routers.kuma.middlewares=kuma-strip,kuma-rewrite"
      - "traefik.http.routers.kuma.priority=100"

      - "traefik.http.services.kuma.loadbalancer.server.port=3001"

      - "traefik.http.middlewares.kuma-strip.stripPrefix.prefixes=/uptime"
      - "traefik.http.middlewares.kuma-rewrite.headers.customresponseheaders.X-Forwarded-Prefix=/uptime"

networks:
  proxy:
    external: true
